all:
	g++ -Wall as_full.cpp io.cpp sim.cpp initial.cpp -o as_full_run
toroidal:
	g++ -Wall -DTOROIDAL as_full.cpp io.cpp sim.cpp initial.cpp -o as_full_run
debug:
	g++ -g -Wall as_full.cpp io.cpp sim.cpp initial.cpp -o as_full_run
debugtoroidal:
	g++ -g -Wall -DTOROIDAL as_full.cpp io.cpp sim.cpp initial.cpp -o as_full_run
